# Generated by Django 4.1 on 2022-08-19 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('shipping', models.CharField(choices=[('online', 'Online'), ('post', 'Post')], max_length=6)),
                ('journal', models.CharField(choices=[('comic', 'Comic'), ('horror', 'Horror'), ('thriller', 'Thriller')], max_length=20)),
                ('myimage', models.ImageField(blank=True, upload_to='media/')),
            ],
        ),
    ]
